remote_theme: rosario/kasper

name: MODELISM
description: Models, templates and tools for managers
meta_description: "Analysis tools and templates"

domain_name: "http://www.modelism.io"

url: ""
author: "Jens Bäckbom"


markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
plugins: [jekyll-paginate]


